### ISSUE TITLE
Not found qpplication

### ISSUE THREAD

**Issue by niqt** [ftylitak/qzxing#108]
With qt 5.12.3 when i compile  my application or this one https://github.com/FelgoSDK/Qt-World-Summit-Conference-App (replacing the source code with the last from github) i have a compiler error, don't found QApplication. Is necessary another compilation flags?

**Comment by ftylitak** [comment]
Hello Nicola, I get the same same error.

Is this the first time that you build with Felgo library? Could it be related with it? 

If it is only from QZXing side, i will try to look it up and provide a solution.

**Comment by ftylitak** [comment]
It seems that by just adding the widgets configuration to the pro file solves the issue:

```pro
QT += widgets
#rest of the original pro file.
```

Does the same applies for you as well?

**Comment by niqt** [comment]
Ok, it works. 
        Thanks
