### ISSUE TITLE
library does not encodes/decodes utf-8 in QR-Code

### ISSUE THREAD

**Issue by 88aleksandr88** [ftylitak/qzxing#109]
I encoded: "Простое предложение."
I decoded: "84MA-I%.GK-IPPQZ:3KKIKXNF$3CH4IKETKYSR"

**Comment by 88aleksandr88** [comment]
As temporary workaround:

Encoding:
```
text = QString::fromLatin1(text.toUtf8());
const QImage imgQrCode240x240L (decoder.encodeData(text));
```

Decoding:
```
QImage imageToDecode("my_image.png");
QString text = decoder.decodeImage(imageToDecode);
text = QString::fromUtf8(text.toLatin1());
```

**Comment by ftylitak** [comment]
hello @88aleksandr88 ,

does this workaround works for you? 

I have seen that if the first letter of the encoded data is not ASCII, the generated QR code is wrong.  This sounds like a bug tath might be starting from https://github.com/ftylitak/qzxing/blob/7678becbb9be6a4c6f95d77e61da37f478c77b60/src/zxing/zxing/qrcode/encoder/QREncoder.cpp#L158. 

I will try to find some time and look it up.
