### ISSUE TITLE
QZXingLive example crash on Qt5.13.0

### ISSUE THREAD

**Issue by xuinvip** [ftylitak/qzxing#112]
QZXingLive example crash
version: Qt5.13.0
platform: mac

**Comment by ftylitak** [comment]
Hello @xuinvip 

can you give me more info. Which commit have you tested? 

Also, do you have any more info on where it crashed? 

I do not own mac so it is a bit difficult to directly test it.

**Comment by xuinvip** [comment]
After Info.plist contain an NSCameraUsageDescription key
