### ISSUE TITLE
Latest master: Build errors MSVC 2017 w/QT 5.12.4

### ISSUE THREAD

**Issue by dlautz314** [ftylitak/qzxing#113]
Seeing some build errors there (with latest commits to DecodeHints.cpp):

DecodeHints.cpp
..\..\..\..\libs\qzxing\src\zxing\zxing\DecodeHints.cpp(203): error C2039: 'inserter': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\atomic(43): note: see declaration of 'std'
..\..\..\..\libs\qzxing\src\zxing\zxing\DecodeHints.cpp(203): error C3861: 'inserter': identifier not found

**Comment by ftylitak** [comment]
hello @dlautz314 

thank you very much for your report. I will look at it as soon as possible.

**Comment by ftylitak** [comment]
@dlautz314 

since i do not have any MSVC compiler setup, can you help be confirm the fix? 

Could you add the following line at the beginning of qzxing\src\zxing\zxing\DecodeHints.cpp file?
```cpp
#include <iterator>
```

If you confirm that it works, I will push it asap. 

Thank you for your assistance.

**Comment by dlautz314** [comment]
Will do. Thanks for the quick response.

**Comment by dlautz314** [comment]
Getting more errors:

UPCEANReader.cpp
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(121): error C2061: syntax error: identifier 'DecodeHints'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(121): error C2511: 'zxing::Ref<zxing::Result> zxing::oned::UPCEANReader::decodeRow(int,zxing::Ref<zxing::BitArray>)': overloaded member function not found in 'zxing::oned::UPCEANReader'
C:\Users\dlautz\work\wickr-desktop\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(30): note: see declaration of 'zxing::oned::UPCEANReader'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(122): error C2065: 'hints': undeclared identifier
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(128): error C2061: syntax error: identifier 'DecodeHints'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(128): error C2511: 'zxing::Ref<zxing::Result> zxing::oned::UPCEANReader::decodeRow(int,zxing::Ref<zxing::BitArray>,const zxing::oned::OneDReader::Range &)': overloaded member function not found in 'zxing::oned::UPCEANReader'
C:\Users\dlautz\work\wickr-desktop\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(30): note: see declaration of 'zxing::oned::UPCEANReader'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(129): error C2597: illegal reference to non-static member 'zxing::oned::UPCEANReader::decodeRowStringBuffer'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(129): error C2440: 'initializing': cannot convert from 'unknown' to 'std::string &'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(131): error C2352: 'zxing::oned::UPCEANReader::decodeMiddle': illegal call of non-static member function
C:\Users\dlautz\work\wickr-desktop\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(67): note: see declaration of 'zxing::oned::UPCEANReader::decodeMiddle'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(133): error C2352: 'zxing::oned::UPCEANReader::decodeEnd': illegal call of non-static member function
C:\Users\dlautz\work\wickr-desktop\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(41): note: see declaration of 'zxing::oned::UPCEANReader::decodeEnd'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(150): error C2352: 'zxing::oned::UPCEANReader::checkChecksum': illegal call of non-static member function
C:\Users\dlautz\work\wickr-desktop\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(79): note: see declaration of 'zxing::oned::UPCEANReader::checkChecksum'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(156): error C2352: 'zxing::oned::UPCEANReader::getBarcodeFormat': illegal call of non-static member function
C:\Users\dlautz\work\wickr-desktop\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(81): note: see declaration of 'zxing::oned::UPCEANReader::getBarcodeFormat'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(156): error C2512: 'zxing::BarcodeFormat': no appropriate default constructor available
C:\Users\dlautz\work\wickr-desktop\libs\qzxing\src\zxing\zxing/BarcodeFormat.h(26): note: see declaration of 'zxing::BarcodeFormat'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(166): error C2228: left of '.decodeRow' must have class/struct/union
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(180): error C2065: 'hints': undeclared identifier
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(180): error C2228: left of '.getAllowedEanExtensions' must have class/struct/union
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(180): note: type is 'unknown-type'
..\..\..\..\wickr-desktop\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(195): error C2228: left of '.lookupCountryIdentifier' must have class/struct/union

**Comment by dlautz314** [comment]
UPCEANReader.cpp
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(121): error C2061: syntax error: identifier 'DecodeHints'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(121): error C2511: 'zxing::Ref<zxing::Result> zxing::oned::UPCEANReader::decodeRow(int,zxing::Ref<zxing::BitArray>)': overloaded member function not found in 'zxing::oned::UPCEANReader'
C:\...\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(30): note: see declaration of 'zxing::oned::UPCEANReader'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(122): error C2065: 'hints': undeclared identifier
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(128): error C2061: syntax error: identifier 'DecodeHints'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(128): error C2511: 'zxing::Ref<zxing::Result> zxing::oned::UPCEANReader::decodeRow(int,zxing::Ref<zxing::BitArray>,const zxing::oned::OneDReader::Range &)': overloaded member function not found in 'zxing::oned::UPCEANReader'
C:\...\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(30): note: see declaration of 'zxing::oned::UPCEANReader'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(129): error C2597: illegal reference to non-static member 'zxing::oned::UPCEANReader::decodeRowStringBuffer'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(129): error C2440: 'initializing': cannot convert from 'unknown' to 'std::string &'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(131): error C2352: 'zxing::oned::UPCEANReader::decodeMiddle': illegal call of non-static member function
C:\...\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(67): note: see declaration of 'zxing::oned::UPCEANReader::decodeMiddle'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(133): error C2352: 'zxing::oned::UPCEANReader::decodeEnd': illegal call of non-static member function
C:\...\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(41): note: see declaration of 'zxing::oned::UPCEANReader::decodeEnd'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(150): error C2352: 'zxing::oned::UPCEANReader::checkChecksum': illegal call of non-static member function
C:\...\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(79): note: see declaration of 'zxing::oned::UPCEANReader::checkChecksum'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(156): error C2352: 'zxing::oned::UPCEANReader::getBarcodeFormat': illegal call of non-static member function
C:\...\libs\qzxing\src\zxing\zxing/oned/UPCEANReader.h(81): note: see declaration of 'zxing::oned::UPCEANReader::getBarcodeFormat'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(156): error C2512: 'zxing::BarcodeFormat': no appropriate default constructor available
C:\..\libs\qzxing\src\zxing\zxing/BarcodeFormat.h(26): note: see declaration of 'zxing::BarcodeFormat'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(166): error C2228: left of '.decodeRow' must have class/struct/union
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(180): error C2065: 'hints': undeclared identifier
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(180): error C2228: left of '.getAllowedEanExtensions' must have class/struct/union
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(180): note: type is 'unknown-type'
..\..\..\..\libs\qzxing\src\zxing\zxing\oned\UPCEANReader.cpp(195): error C2228: left of '.lookupCountryIdentifier' must have class/struct/union

**Comment by ftylitak** [comment]
@dlautz314  

can you pull the latest code from master and confirm that is now fixed?

**Comment by dlautz314** [comment]
Will do. Thanks.

**Comment by dlautz314** [comment]
Looks good, qzxing built and linked, seems to be functioning correctly.

Thanks again.

**Comment by ftylitak** [comment]
Thank you very much for reporting the issue.

Regards
