### ISSUE TITLE
Decoding string scanned by barcode scanner (laser)

### ISSUE THREAD

**Issue by yanis60** [ftylitak/qzxing#114]
Hi,
I discovred your project and i want to use it in y software application that manages barcodes.

I scan barcodes using laser scanner (not camera) so can i decode string directly scanned from laser scanner??

**Comment by ftylitak** [comment]
Hello @yanis60 

to my knowledge, lazer barcode scanners do have their own API to retrieve the data from the detected barcode. 

QZXing is only for barcode readers that are based on camera image capturing, hence the library gets as input a QImage. A lazer barcode scanner does not work that way.  

Leaving aside that what you are looking for does not relate to this project, would you like to share the model of the lazer barcode scanner? May be someone could have a hint to give you .

**Comment by yanis60** [comment]
too bad :(, it's an excellent project.

my project uses a generic lazer scanner, he retrieves only the barcode string, that why i'm asking if your software is able to decode from string value.

**Comment by ftylitak** [comment]
@yanis60 

when you mention "decode from string value" what exactly do you want to do? 
I understand that you already get the string from the barcode reader. What more do you want after that?

**Comment by yanis60** [comment]
I want to get the product informations, some products contains datamatrix barcode with some hidden informations on it.
That why i need to decode it

**Comment by yanis60** [comment]
Can i generate datamatrix image using your project??
Using the generated image i can get the informations containing by the datamatrix code

**Comment by ftylitak** [comment]
Only Qr Code encoding is supported for the moment so this will not help you. 

Though, may be you would be interested in using an internal class of ZXing. 

Looking at the following part of [DataMatrixReader](https://github.com/ftylitak/qzxing/blob/master/src/zxing/zxing/datamatrix/DataMatrixReader.cpp), you can see that it first extracts the bits and then it decodes them:
https://github.com/ftylitak/qzxing/blob/39c9b04697501dfc1c86ca9aefb778106c3d451f/src/zxing/zxing/datamatrix/DataMatrixReader.cpp#L35-L48

Then, based on the line 42 you see that the DataMatrixDecoder is used possibly for the operation that you are seeking: 

https://github.com/ftylitak/qzxing/blob/39c9b04697501dfc1c86ca9aefb778106c3d451f/src/zxing/zxing/datamatrix/decoder/DataMatrixDecoder.cpp#L65

Using this as a guide you could write something like:
```cpp
//lets assume you have the raw bites provided by the laser barcode reader
std::vector<byte> rawBytes; 

//create a BitMatrix using the rawBytes
Ref<BitMatrix> rawBitMatrix = new BitMatrix(/*width*/, /*height*/);
//copy your data to the rawBitMatrix
...

Ref<DecoderResult> decoderResult(decoder_.decode(detectorResult->getBits()));

Ref<Result> result(
    new Result(decoderResult->getText(), decoderResult->getRawBytes(), points, BarcodeFormat::DATA_MATRIX));

return result;
```

Could this approach help you anyhow?
