### ISSUE TITLE
Problem with Android and Qt 5.13

### ISSUE THREAD

**Issue by DragonicUA** [ftylitak/qzxing#122]
Works well on Qt 5.12.
On Qt 5.13 logs are:

```
QZXingFilterRunnable error: Cant create image file to process.
Maybe it was a format conversion problem?
VideoFrame format:  Format_ABGR32
Image corresponding format:  QImage::Format_Invalid
```

**Comment by ftylitak** [comment]
Hello @DragonicUA 

thank you for your report. Indeed i confirm your issue. I will look it up soon.

**Comment by ftylitak** [comment]
@DragonicUA 

do you confirm that the issue has been solved?

**Comment by DragonicUA** [comment]
yes, thank you

**Comment by Auramel** [comment]
I have the same problem. Qt 5.15

```
Image corresponding format:  QImage::Format_Invalid
QZXingFilterRunnable error: Cant create image file to process.
Maybe it was a format conversion problem?
VideoFrame format:  Format_ABGR32
```

**Comment by ftylitak** [comment]
@Auramel, do you use the latest code from the master branch?

**Comment by Auramel** [comment]
@ftylitak 
![image](https://user-images.githubusercontent.com/5775873/89782618-17f37b00-db2f-11ea-9c2e-6d95d124b3b9.png)

**Comment by ftylitak** [comment]
@Auramel the fact that you are on master branch does not mean that it is with the latest code. 
Your error as I can interpret it is that in QZXingFilter you are missing the case of QVideoFrame::Format_ABGR32 which was added a year ago. 

Do the following to get the latest:
```
git pull origin master
```

**Comment by Auramel** [comment]
@ftylitak I've already done it, after clone repo.

**Comment by ftylitak** [comment]
Ok then, could you open your local copy of the src/QZXingFilter.cpp and search for the QVideoFrame::Format_ABGR32 ? 
Is it in there? If it is, could you remove the preprocessor macros (the #if #endif) and give it a try?

https://github.com/ftylitak/qzxing/blob/4715b242cc08582a0c31aad94d74251b77821a29/src/QZXingFilter.cpp#L278-L280

**Comment by Auramel** [comment]
@ftylitak Fuck, I'm so sorry. I'm using `Eism/qzxing`. I didn't notice it.

**Comment by ftylitak** [comment]
@Auramel it's ok :) i was sure that something like this should be the reason or else you would have other issues.
