### ISSUE TITLE
fatal error: QtCore/QtGlobal: No such file or directory on Ubuntu 16.04 and Qt 5.13

### ISSUE THREAD

**Issue by nejatafshar** [ftylitak/qzxing#123]
I have added QZXing as subdirs project and link to it in my app on Ubuntu 16.04 and Qt 5.13. QZXing compiles normally but my app gives compile error as:

```
In file included from 3rdparty/QZXing/src/QZXing.h:20:0,
                 from 3rdparty/QZXing/src/QZXing.cpp:1:
3rdparty/QZXing/src/QZXing_global.h:20:10: fatal error: QtCore/QtGlobal: No such file or directory
 #include <QtCore/QtGlobal>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
I am using latest code from master and linking to QZXing properly. Using QZXing by adding `QZXing.pri` to my project .pro file produces the same error. Both approches in using QZXing works fine on Windows. I had not this issue with Qt 5.12.

**Comment by ftylitak** [comment]
Hello @nejatafshar 

have you seen this comment? https://github.com/ftylitak/qzxing/issues/118#issuecomment-510941104

I am still uncertain what exactly causes this error, though it surely has to do something with the Qt configuration of each one.

**Comment by ftylitak** [comment]
Can you try adding the following line to the QZXing.pri?

```pro
QT += widgets
```

**Comment by nejatafshar** [comment]
@ftylitak Added `QT += widgets` to QZXing.pri. Still it gives me the same error. Have seen the comment you mentioned but I did not get what he has done exactly.

**Comment by nejatafshar** [comment]
@ftylitak I managed to solve the problem by changing the include line for QZXing in my app from `#include <QZXing>` to `#include "QZXing.h"`.

**Comment by ftylitak** [comment]
Closing the issue as it should already be resolved by https://github.com/ftylitak/qzxing/commit/10ba99586e955ae1be12114fb7a7bb60e0ba809e. 

In case of futher errors, please open a new issue.
