### ISSUE TITLE
Scanning of QR codes failing (randomly) for us on latest master, but happens for demo as well.

### ISSUE THREAD

**Issue by dlautz314** [ftylitak/qzxing#129]
We have been using Qzxing for awhile now in our application, but recently we updated to latest master (mainly we needed updates to move to MSVC 2017 & QT 5.12.4).

Now we are experiencing issues on MacOS (High Sierra), where Qzxing fails to scan valid QR codes. This can be inconsistent at times, where same code will sometimes scan. But we have not seen this previously, and when we revert to older version of our application (using older tag from Qzxing repo, Jan 12 2018, commit f4740d6e44fab3b4c74430b225c19c477fbb37ef), the problem does not happen.

Additionally, I try to scan the same code using QZXingLive example application, and the same QR code will not scan either.

I have attached the QR code I used to test. Any help is greatly appreciated.

Thanks.

![QRDontScan](https://user-images.githubusercontent.com/27902664/62956534-19c21b80-bdc1-11e9-80d7-96019d166c46.jpg)

**Comment by dlautz314** [comment]
I believe pull request https://github.com/ftylitak/qzxing/pull/130 fixes this issue, it would be appreciated if this could be reviewed and committed as soon as possible.

Thanks.

**Comment by ftylitak** [comment]
Hello @dlautz314,

#130 is now merged. Can you check whether your issue is resolved?

**Comment by dlautz314** [comment]
Yeah, working great now, thanks!
