### ISSUE TITLE
QML Encode QRCode with '\n' is not a new line

### ISSUE THREAD

**Issue by reesaakbar** [ftylitak/qzxing#134]
There is no problem to encode QRCode with '\n' under QT 5.13 in QML. However, the result were not what I expected.

For example

```
 property string strQr: "hello\nword" 
 
    ....
              Image{

                 visible: true
                 id:imageqr
                 source: "image://QZXing/encode/" + strQr +
                         "?corretionLevel=L" +
                         "&format=qrcode"
                 sourceSize.width: column1.width/1.5
                 sourceSize.height: column1.width/1.5
                 anchors.horizontalCenter: parent.horizontalCenter
             }
 ....
```
 
In the detector result, '\n' is converted to '%0A'
 ```
hello%0Aworld
```
how to code in QML in order to obtain a "real" new line, such as:
```
 hello
 world
```
Thank you

**Comment by cily-sybersense** [comment]
Hello, did you find solution ?

**Comment by ftylitak** [comment]
@cily-sybersense and @reesaakbar 

i have just pushed a fix to this issue. Can you please test and confirm that it works for you?

**Comment by reesaakbar** [comment]
> @cily-sybersense and @reesaakbar
> 
> i have just pushed a fix to this issue. Can you please test and confirm that it works for you?

**Comment by reesaakbar** [comment]
@ftylitak 

Okay. I will test it.

**Comment by reesaakbar** [comment]
@ftylitak and @cily-sybersense 

It works well. Thank you for the latest fix.
