### ISSUE TITLE
Barcode scan not work with QZXingFilter

### ISSUE THREAD

**Issue by nikosvr88** [ftylitak/qzxing#138]
Hi, i am trying to read a barcode when my camera pass over the barcode (without take a picture) but no success. I've tried the same with image captture and worked. Any ideas?

**Comment by ftylitak** [comment]
(adding here the link of the source code that you provided in the issue #137 ) 

https://github.com/ftylitak/qzxing/issues/137#issuecomment-533529246

**Comment by ftylitak** [comment]
Have you tried to use and test the QZXingLive example? Does it work for you?

Secondly, what barcode are you trying to decode? By defalut, upon creation of QZXingFilter, it has only the QR code decoding enabled. If you are trying to decode other types of barcodes, you first need to enable the decoders as follows: 

```qml
    QZXingFilter
    {
        ...
        decoder {
            enabledDecoders: QZXing.DecoderFormat_EAN_13 | QZXing.DecoderFormat_CODE_39 | QZXing.DecoderFormat_QR_CODE
            ...
        }
    }
```

**Comment by ftylitak** [comment]
@nikosvr88  do you have any update on this?

**Comment by ftylitak** [comment]
Closing due to ina.ctivity
