### ISSUE TITLE
the image encode by qzxing can't be decode

### ISSUE THREAD

**Issue by bird1978** [ftylitak/qzxing#142]
when encode the string as bellow:
QString info="C9789DBAFAA5FE3BE5CD0FA64DBEB5897302A94D09EBC4D83E5D824459A601F72759693D26EFBD4530D8458836C7EC787A0C09C3292D66AA3570DB071EE7C4EA37E2D1A415836D28EC742A2CCD31FBD7EF6C790688E0A3E4BCACBCCDDSDSA2CAE87BFE72D3E275794E88909CBAF3F311804CAE1A7FBB070D67C476BD3E082AEE7492DF93BC5FE949AF89450A10030EA8FEC75730CBB8FFDA5FC48F28F8DC1F988B29514B963BB0AC6FB8322724B3DC8F6FBDDFA872183FDE04693EE8A";
 QZXing encode;
QImage image=encode.encodeData(info,QZXing::EncoderFormat_QR_CODE,QSize(480,480),QZXing::EncodeErrorCorrectionLevel_L,true);

the image can't be decoded .

**Comment by ftylitak** [comment]
hello @bird1978 

indeed this is a known bug and is related to #83 .

The encoding of Qr code with error correction level to L (Low) has currently limit to around 105 characters. 

It is a bug that I would like to be fixed, though I have not yet found the solution.
