### ISSUE TITLE
QZXingLive throw segfault on Raspberry Pi

### ISSUE THREAD

**Issue by deniseBrise** [ftylitak/qzxing#143]
Executing QZXingLive on my raspberry (Raspberri Pi 2, Raspbian Stretch, Qt 5.12.5) leads to segmentation fault just after showing video output.

```
$ ./QZXingLive 
QML debugging is enabled. Only use this in a safe environment.
[9;0]Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).

** (QZXingLive:17386): CRITICAL **: gst_audio_format_from_string: assertion 'format != NULL' failed
Focus mode selection is not supported
needed to resize
size:  0 , new size:  1536000
Erreur de segmentation
```

If I comment the "captureRect:" section, app is working properly.

**Comment by deniseBrise** [comment]
Hello @ftylitak, and thanks for your quick reply
Indeed, I am using an USB camera. I have joined GDB's backtrace and full strace output.
[backtrace.txt](https://github.com/ftylitak/qzxing/files/3760655/backtrace.txt)
[strace.txt](https://github.com/ftylitak/qzxing/files/3760620/strace.txt)

**Comment by ftylitak** [comment]
Hell @deniseBrise 

proper implementation for the image format that raspberry produces (YUV420P) was mistakenly deleted at a refactoring. 

Can you pull the latest changes from master and test again? 

On my Raspberry Pi 2 with Qt 5.12.4 it worked. 

Waiting for your input.

**Comment by deniseBrise** [comment]
Thanks, now it's working perfectly on my Pi :)

**Comment by ftylitak** [comment]
Perfect! Thank you for your report.
