### ISSUE TITLE
after updating openssl to 1.1.1d the scanner is not working anymore.

### ISSUE THREAD

**Issue by goldeneyexby** [ftylitak/qzxing#144]
Ou app has been using the QR scanner for almost a year now without issues. We updated the openssl libraries recently to openssl 1.1.1d and now the QR scanner doesn't recognize any QR codes. Is it possible that there is an incompatibility with the update openssl libraries?

**Comment by ftylitak** [comment]
Greetings @goldeneyexby 

should I guess that your app is targeting Android? 

I do not have any guess for now though I will look it up.

**Comment by goldeneyexby** [comment]
We are targeting Android. We are using Qt 5.12.5 and Android ndk r19c.

**Comment by ftylitak** [comment]
@goldeneyexby one question. Do you happen to use Felgo library as well in your application?

**Comment by ftylitak** [comment]
I have hust compiled and run the QZXingLive with Qt 5.12.5, with the latest openssl targeting Android ARM64-v8a and it works without issues. 

So, next question would be :
 * Did you compile the application with Qt 5.12.5 Android ARMv7? or ARM64-v8a?
 * Did you manually compile the openssl to the same architecure as the Qt? (ARMv7 or ARM64-v8a)?

**Comment by goldeneyexby** [comment]
We compiled it for Android ARMv7 and we compiled the openssl libraries manually to the same architecture. We did however got it working again, adding the "tryharder=true" parameter did the trick.

**Comment by ftylitak** [comment]
Hmmm ok, it does not sound ideal though if it works, this is good. Performance-wise is it the same as before your update? 

Overall, if this solution is ok for you, should I consider this as closed?

**Comment by ftylitak** [comment]
Closing the issue. If there is still an issue, please open a new one.
