### ISSUE TITLE
[meta] Consider splitting tests into another git repo.

### ISSUE THREAD

**Issue by lhy0403** [ftylitak/qzxing#149]
I'm currently using qzxing within one of my projects, it's using git submodule to clone dependencies.
After publishing the project to the AUR (Archlinux User Repository), my users reported it takes long to pull out this library.

Currently, I forked this repository and removed all tests from it, pushed to [my own repo](https://github.com/lhy0403/qzxing_noTests), but it cannot let me track the upstream's (which is in this repo) bug fixes. (**Especially this: https://github.com/ftylitak/qzxing/commit/10ba99586e955ae1be12114fb7a7bb60e0ba809e**)

It's pretty annoying for people whose internet connection is not fast, the test takes up nearly 90% in the size of the repo.
Tests are useless for the users of this repo since they only need the `.pri` file as a dependency in the project, not to test the library itself.

I suggest moving the `tests` folder into another repository and clone it whenever required and cleaning up the git history to make sure the git blobs are fully removed from history.

What do you think about it, sir @ftylitak ?

**Comment by ftylitak** [comment]
Hello @lhy0403 

i understand your point. Using this project as a submodule will download tests as well. 

If I were to move the tests into an other branch, I believe that would be sufficient for your needs. 
What is your opinion on that?

**Comment by lhy0403** [comment]
Thanks for your quick reply. 😊

I'm not sure of branches containing blobs will be cloned as well using `git submodule update --init` may be using `--depth` may help?

**Comment by lhy0403** [comment]
When this fix would be applied sir?
I don't mean to force anyone, but it really blocks my build these days 😂

Thanks!

**Comment by ftylitak** [comment]
@lhy0403 I will look at it now. 

Though I do not see how this suggestion of splitting the code and tests gets to relate to the issue that you have posted. I do not see how this is "blocking" your building process. 

Anyhow, I will update you soon.

**Comment by lhy0403** [comment]
It's not actually "blocking" my bugfix, I'll switch git submodule to the official `qzxing` repo (that is, yours) but I don't want to spend time cloning the tests though, I'm just waiting for your migration happen and so the `#include <>` issue could be resolved.

Thanks for your reply. @ftylitak 

Yeah it might be caused by my bad English skill (xD)

**Comment by ftylitak** [comment]
So, I moved only the test resources to an other repository which is now a submodule for the QZXing library, for those that want to run the tests. 

Does this solution solves your problem?

**Comment by lhy0403** [comment]
Yes, the only thing I need will be appending `--depth=1` to my `git submodule update --init`.

It already resolved my problem, Thanks!

**Comment by lhy0403** [comment]
Thanks! 
I may confirm it's now ready to use.
Thanks!

**Comment by ftylitak** [comment]
You are welcome.
