### ISSUE TITLE
Some QR codes cannot be detected.

### ISSUE THREAD

**Issue by Qv2ray-dev** [ftylitak/qzxing#152]
[73586041-26f3d380-44e3-11ea-9cf3-a4a8bb993087](https://user-images.githubusercontent.com/59914293/73587210-16982480-44f4-11ea-8f9d-6f721ab3c712.png)
This file, when displaying in its real size, cannot be detected by QZxing, however, scaling it down a **tiny** bit, even make it 99% of its original size, (just do it in a browser, or using some image tool) will make it able to be detected.

ZBar has no problem reading such file and the same results can be obtained in some online detectors at https://zxing.org/w/decode and https://online-barcode-reader.inliteresearch.com/

Upstream issue: https://github.com/Qv2ray/Qv2ray/issues/293

**Comment by ftylitak** [comment]
Hello @Qv2ray-Bot 

thank you for reporting this issue. Part of the QR code detection code has been aligned with the latest code of zxing project so this resolves your special case. 

Give it a try and I look forward to your feedback.

**Comment by Qv2ray-dev** [comment]
Sorry for the long delay, our project was being refactored during these days so we cannot test.

For now, I can say it's been fixed for at lease scanning the image above using QZxing gives the correct result.!

Thanks.
