### ISSUE TITLE
Fix QTime deprecation warning

### ISSUE THREAD

**Issue by martonmiklos** [ftylitak/qzxing#157]
As of Qt 5.14 the QTime::elapsed/start/restart marked elapsed see:
https://github.com/qt/qtbase/commit/ed99a591a83a399458f12341d0a1c0b3152f247a

@ftylitak 
If you agree on porting these calls to QElapsedTimer I will submit a PR. (QElapsedTimer is in Qt since 4.7 so I think it is safe to rely on that.)

**Comment by ftylitak** [comment]
@martonmiklos

this is already addressed by #150 so if you pull the latest of master you should be fine. 

But either way, thank you very much for offering your time for the PR.
