### ISSUE TITLE
Bug in function ImageHandler::extractQImage()

### ISSUE THREAD

**Issue by antonio-111** [ftylitak/qzxing#159]
```cpp
//File ImageHandler.cpp, line 54
//Now:
img = result->image();
//Must be:
if (result)
    img = result->image();
```
result is QSharedPointer and is accessed without checking for nullptr.
When loading an invalid image, it is nullptr.

**Comment by ftylitak** [comment]
hello @antonio-111 

I saw the PR that you have sent #160 and you have correct approach. 
Should I make one suggestion, why not place the check that you propose earlier? 

that is: 

```cpp

/*line 38*/  QSharedPointer<QQuickItemGrabResult> result = item->grabToImage();
if (result) 
{
..
//contain the code of lines: 39-67
}
```

Update you PR with this change and I will merge it.
