### ISSUE TITLE
Program crashes when empty vector is passed to FinderPatternInfo constructor.

### ISSUE THREAD

**Issue by antonio-111** [ftylitak/qzxing#164]
Program crashes when empty vector is passed to FinderPatternInfo constructor.
Here is my call stack:
![Screenshot from 2020-03-18 23-52-11](https://user-images.githubusercontent.com/36404162/77006688-f6250c00-6973-11ea-8c54-fe4dd80298c7.png)

**Comment by ftylitak** [comment]
Thank you @antonio-111  for the report! 

Do you have any sample image that reproduces this segmentation? Or do you have any recommendation on how to reproduce this?

**Comment by ftylitak** [comment]
@antonio-111 

i have just pushed a small change with an extra check to avoid the segmentation. Though, I am still uncertain whether there is an actual issue somewhere else that gets hidden by this check. 

In any case, as I said to my previous post, if you have sample images that could reproduce the issue would be more than welcomed. 

Looking forward to your feedback.

**Comment by antonio-111** [comment]
I caught this case while processing stream from my camera to recognize and decode QR code. I think it was accidental image. So unfortunately no image and no scenario to reproduce.

**Comment by ftylitak** [comment]
@antonio-111 by streaming from the camera of the smartphone I have reproduced this issue and the fix that I uploaded at least  rejects these cases and the application does not crash. 

Should I consider this issue fixed?

Did you do any tests on your own?

**Comment by rdobrokhotovomp** [comment]
Hi,
I have the same issue.
It's often reproduced when there are several QR-codes on the screen.

**Comment by ftylitak** [comment]
I consider this as closed as it was reproduced and fixed. In case you experience the same problem again, feel free to re-open the issue.
