### ISSUE TITLE
QZXing , Qt5.14.1 and Android gives GL_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by vdaele** [ftylitak/qzxing#165]
This is mainly to inform you that I created a Qt bug (https://bugreports.qt.io/browse/QTBUG-83149)
I don't think this is an error on your side but maybe it is also interesting for you.

I first ran the QZXingLive  example using Qt5.12.7
Afterwards I compiled it for Qt5.14.1.  In order to do so, I had to make the following changes
- increase the minimum required SDK to 21 9in AnroidManifest.xml)
- change the NDK from r19c to r21.0.6 (I got a compiler error on including type_traits)
- the resulting binary crashed:  I had to regenerate the Android Templates ("Create templates" button in Projects/build/Build android apk) because there are changes related to loading libs in the AndroidManifest.xml; 
  - afterwards, I've adjusted the package name again to org.ftylitak.qzxing
- finally I had a problem with "import android.support.v4" in Utilities.java (probably due to the higher gradle version?). 
  - I took a shortcut here and removed everything in Utilities.checkAndRequestPermissionList (except the last line);
  - This worked for me since I already had the permissions from the previous 5.12.7 run

When running the resulting binary I see 

```
W GLConsumer: [SurfaceTexture-0-5539-0] bindTextureImage: clearing GL error: 0x505
W Adreno-ES20: <core_glDrawArraysInstancedXXX:929>: GL_OUT_OF_MEMORY
W GLConsumer: [SurfaceTexture-0-5539-0] bindTextureImage: clearing GL error: 0x505
W Adreno-ES20: <core_glDrawArraysInstancedXXX:929>: GL_OUT_OF_MEMORY
W GLConsumer: [SurfaceTexture-0-5539-0] bindTextureImage: clearing GL error: 0x505

```

**Comment by ftylitak** [comment]
Great @vdaele ,

I am curious to learn the route cause. 

Look forward to hear further updates.

**Comment by jnpStimio** [comment]
Hi,
You could try the last Qt 5.14.2 update, because it fixes some OpenGL issues with Camera.

**Comment by vdaele** [comment]
Tx for the suggestion!
I can confirm that 5.14.2 works fine!  I'll also update the corresponding
QtBug!

Marc
