### ISSUE TITLE
No detection on Android with Data Matrix 

### ISSUE THREAD

**Issue by jnpStimio** [ftylitak/qzxing#166]
Hi,

I used QZXing on Android device, and it works perfectly with QR Codes.
But I have no detection with Data Matrix on Android, whereas the build with Desktop emulator works.
I have no error logs even in Debug.

What's wrong ? 

(Qt 5.14.2)
Flag used for Data Matrix: ``QZXing.DecoderFormat_DATA_MATRIX``
Data Matrix used: [Link](https://barcode.tec-it.com/barcode.ashx?data=This+is+a+Data+Matrix+by+TEC-IT&code=DataMatrix&multiplebarcodes=false&translate-esc=false&unit=Fit&dpi=96&imagetype=Gif&rotation=0&color=%23000000&bgcolor=%23ffffff&codepage=&qunit=Mm&quiet=0&dmsize=Default).

**Comment by jnpStimio** [comment]
News:
For an unknown reason, Qt Creator decided to stop to deploy the new build with "Data Matrix" mode.
I reopened Qt Creator and all works...

**Comment by ftylitak** [comment]
Perfect! Glad to hear it works!
