### ISSUE TITLE
Unnecessary CMake version dependency

### ISSUE THREAD

**Issue by dobey** [ftylitak/qzxing#167]
The features used in qzxing for the CMake build are quite simple, and it seems the version increase was not necessary. The higher version dependency makes building on Ubuntu 16.04 and other platforms which still have older CMake versions, unnecessarily complex and difficult.

When this change happened, there were also new variables defined in the main `CMakeLists.txt` which are not used anywhere. It seems that perhaps a change in newer CMake which makes specifying full path when adding sources to a target from a sub-directory's `CMakeLists.txt` unnecessary, is perhaps what lead to the new version dependency. Relaxing the dependency and providing the full paths in the sub-directories is possible, though, allowing easy builds on other platforms.

**Comment by ftylitak** [comment]
@dobey thank you very much for your fix! It is quite usefull!
