### ISSUE TITLE
Detection of Inverted QR Code 

### ISSUE THREAD

**Issue by russkij76** [ftylitak/qzxing#171]
Hi there,

how can I handle inverted barcodes?

Best regards
Alex

**Comment by russkij76** [comment]
Hello @ftylitak,

thanks, I need both variants, with the change inverted codes work.
A new flag would be very nice :-)

efcharisto
Regards
Alex

**Comment by ftylitak** [comment]
@russkij76 

I just pushed a change that you can configure whether to scan the normal image, the inverted image or both. It is in a separate branch but you could give it a try. 

QML example (imageSourceFilter variable): 
```qml
 QZXing{
        id: decoder
        //tryHarderType: QZXing.TryHarderBehaviour_Rotate //| QZXing.TryHarderBehaviour_ThoroughScanning
        imageSourceFilter: QZXing.SourceFilter_ImageNormal | QZXing.SourceFilter_ImageInverted

        onTagFound: {
            log.add("Tag found: " +tag+ ", milliseconds: " + processingTime)
        }
    }
```

C++ example: 
```cpp
QImage imageToDecode("file.png");
QZXing decoder;
decoder.setSourceFilterType(QZXing::SourceFilter_ImageNormal | QZXing::SourceFilter_ImageInverted)
decoder.setDecoder( DecoderFormat_QR_CODE | DecoderFormat_EAN_13 );
QString result = decoder.decodeImage(imageToDecode);
```

**Comment by russkij76** [comment]
@ftylitak 

thank you, it works!

**Comment by ftylitak** [comment]
This has been merged to master so I will close the issue.

**Comment by russkij76** [comment]
maybe remove the lines?
qDebug() << "Start decoding *";
qDebug() << "End decoding 1";

**Comment by ftylitak** [comment]
Hello @russkij76 

thanks for the suggestion. I would recommend pulling the latest version as I have removed the debug messages and made a fix in the selection of Inverted Image feature.
