### ISSUE TITLE
Segmentation Fault in QRFinderPatternFinder.cpp

### ISSUE THREAD

**Issue by jw23578** [ftylitak/qzxing#179]
Hi, sometimes i got a segmentation fault at
`Ref<FinderPatternInfo> result(new FinderPatternInfo(patternInfo));`
in `Ref<FinderPatternInfo> FinderPatternFinder::find(DecodeHints const& hints)`

The Reason is that patternInfo.size() is 0 so i added this:
```
  if (patternInfo.size() < 3) {
    throw zxing::ReaderException("no possible centers found");
  }
```
after
`  vector< Ref <FinderPattern> > patternInfo = selectBestPatterns();`

Lines 519 to 538 in QRFinderPatternFinder.cpp:

  ```
if(this->possibleCenters_.size() < 3) {
    throw zxing::ReaderException("no possible centers found");
  }

  vector< Ref <FinderPattern> > patternInfo = selectBestPatterns();

  if (patternInfo.size() < 3) {
    throw zxing::ReaderException("no possible centers found");
  }

  vector< Ref <ResultPoint> > patternInfoResPoints;

  for(size_t i=0; i<patternInfo.size(); i++)
      patternInfoResPoints.push_back(Ref<ResultPoint>(patternInfo[i]));

  ResultPoint::orderBestPatterns(patternInfoResPoints);

  patternInfo.clear();
  for(size_t i=0; i<patternInfoResPoints.size(); i++)
      patternInfo.push_back(Ref<FinderPattern>(static_cast<FinderPattern*>( &*patternInfoResPoints[i] )));

  Ref<FinderPatternInfo> result(new FinderPatternInfo(patternInfo));
  return result;
}

```
now i do not get any more segmentation faults

**Comment by ftylitak** [comment]
Hello @jw23578 

you are correct to your approach. Though I believe that most likely you did not have the latest commit of the master branch since this was addressed 10 commits ago here: https://github.com/ftylitak/qzxing/commit/cf3391027b7e422dd7b1f9a8678da731273835dc

**Comment by ftylitak** [comment]
Closing due to no further info.
