### ISSUE TITLE
Issues with Visual Studio 2017 x64 runtime

### ISSUE THREAD

**Issue by bleze** [ftylitak/qzxing#183]
Hi

Help, I'm stuck :)

First I built DLL, but no LIB file is created? Kind of hard to use then :)

Then I changed to staticlib instead, which will build a LIB file, however when using it in a project I get linker errors. Seems the dependency on VC2017 is broken;

`LNK2001	unresolved external symbol __CxxFrameHandler4`

Anyone know how to get LIB built either as dynamic or static with dynamic linking to runtime (which seems static now and I think it conflicts with my dynamic usage is application)?

I'm pretty sure my Qt Creator is using correct toolset; ABI: x86-windows-msvc2017-pe-64bit

Looking at compilers, this ABI is listed for; Microsoft Visual C++ Compiler 15.9.28307.1259 (amd64).

My Visual Studio version is 15.9.27.

Thanks in advance!

**Comment by ftylitak** [comment]
hello @bleze  and sorry for the late reply.

indeed it was an issue in the QZXing.pro file. Currently the file ends with:
```pro
DEFINES -= DISABLE_LIBRARY_FEATURES

include(QZXing-components.pri)
```

whereas it need to be:

```pro
include(QZXing-components.pri)

DEFINES -= DISABLE_LIBRARY_FEATURES
```

after the change, do a rebuild and it should be working now.

Thank you for reporting it.

**Comment by bleze** [comment]
Hi ftylitak

Thanks and I can confirm that this helped. I managed to create a dynamic build with no further issues. Please remember to commit change ;)

Thanks again!
