### ISSUE TITLE
Undefined reference to 'QZXingImageProvider::QZXingImageProvider()'

### ISSUE THREAD

**Issue by sifatron** [ftylitak/qzxing#184]
Hi guys,

Running into issue trying to run QZXing(core + QML).

I am getting this error when I am trying to build:

`Undefined reference to 'QZXingImageProvider::QZXingImageProvider()'`

This is where I am getting the error:
`void QZXing::registerQMLImageProvider(QQmlEngine& engine)
{
    engine.addImageProvider(QLatin1String("QZXing"), new QZXingImageProvider());
}`

**Any idea why this might be happening?**

I copied the source code folder of QZXing to the root of my project. and added the following lines to my .pro file.
`include(QZXing/QZXing.pri)`
`CONFIG += qzxing_qml`

This is what i added to my main.cpp:
```
#include "QZXing.h"

int main() 
{
    QString data = "text to be encoded";
    QImage barcode = QZXing::encodeData(data);

    ...
    QZXing::registerQMLTypes();
    ...

}
```

Add the following to my desired qml file:
```
import QZXing 2.3

TextField {
	id: inputField
	text: "Hello world!"
}

Image{
	source: "image://QZXing/encode/" + inputField.text;
	cache: false;
}
```

Please let me know if I am missing anything.

**Comment by ftylitak** [comment]
@sifatron 

you just need to reorder the declarations of CONFIG and include in the pro file. The correct order is:

```
CONFIG += qzxing_qml
include(QZXing/QZXing.pri)
```

**Comment by sifatron** [comment]
@ftylitak

Thank you so much. I solved the issue. Thank you so much.

Now I am being able to build the project, but the image is not showing up.

I added `import QZXing 2.3` as mentioned and also added `QZXing::registerQMLTypes()` to my main. 

```
        Image {
            anchors.fill: parent
//            fillMode: Image.PreserveAspectFit

            source: "image://QZXing/encode/" + qrcodeInput.text // + "?correctionLevel=M" + "&format=qrcode";
            cache: false
//            sourceSize.width: 200
//            sourceSize.height: 200
        }
```
I tried both default and custom settings, but the qr code image is not showing up. I am not sure why it is not generating the output qr code. Since your answer did solve the initial issue that I posted, should I create a new issue?

**Comment by ftylitak** [comment]
@sifatron 

you run into a case of missing info from the README file. I will update it as soon as possible. 
To solve your case, in your main.cpp, after __QZXing::registerQMLTypes();__ add __QZXing::registerQMLImageProvider(engine);__

```cpp
 ...
QZXing::registerQMLTypes();
QZXing::registerQMLImageProvider(engine);
...
```

**Comment by sifatron** [comment]
@ftylitak

Thank you for your kind support. Really appreciate it.

I had already tried adding `QZXing::registerQMLImageProvider(engine);` after `QZXing::registerQMLTypes();`
But it didn't change anything. As you can see from my previous comment, I am using QQuickView view and using setSource to load my qml. I even changed that to `engine.load(QUrl(QStringLiteral("qrc:/qml/main.qml")));` to load my qml. But even then it is nor working.

In my qml file, I am have the following imports:
```
import QtQuick 2.12
import QtQuick.Controls 2.3
import QZXing 2.3
```
Is there any other dependency? Should I be using QtQuick.Control 1.x? 

Also, in my main, as you can see from my previous comment, I am using `QQmlApplicationEngine engine;` and `QQuickView view;` Can it be because of either one of these objects?

**Comment by ftylitak** [comment]
The QQmlApplicationEngine that you defined in the main has no usage since you try to load the qml files with QQuickView. Also you both use QApplication and QGuiApplication. I believe you should stick with QGuiApplication.
Using the following main, does it work for you?

```cpp
int main(int argc, char *argv[])
{
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;

    QZXing::registerQMLTypes();
    QZXing::registerQMLImageProvider(engine);

    engine.load(QUrl(QLatin1String("qrc:/main.qml")));

    return app.exec();
}
```

or if you want to stick with your main.cpp, may be the following could work:

```cpp
int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);
    QGuiApplication::setOverrideCursor(QCursor(Qt::BlankCursor));
    QQuickView view;
    QTranslator translator;
    ...
    QZXing::registerQMLTypes();
    QZXing::registerQMLImageProvider(*view.engine());
    ...
    view.setSource(QUrl(QStringLiteral("qrc:/qml/main.qml")));
    view.show();
    return app.exec();
}

```

**Comment by sifatron** [comment]
@ftylitak 

Thanks for pointing that out. I actually intended to only use QGuiApplication, so got rid of QApplication.
I tried both the solutions, using QQmlApplicationEngine and QQuickView as you mentioned in your comment. In both cases the same result, no image is showing up. I am using Qt 5.12.1 right now. Not getting any errors or warnings during compile output.

**Comment by ftylitak** [comment]
Ok most likely then you have a bug in your qml file.
Could you try the following main.qml and see if it works for you?

```qml
import QtQuick 2.0
import QtQuick.Controls 2.0
import QtQuick.Layouts 1.3
import QtQuick.Dialogs 1.3

ApplicationWindow {
    id: mainWindow
    visible: true
    width: 640
    height: 480

    ColumnLayout {
        id: mainLayout
        anchors {
            fill: parent
            margins: 10
        }

        TextArea {
            id: inputField
            Layout.fillWidth: true
            selectByMouse: true
            text: "Hello world!"

            Rectangle{
                anchors.fill: parent
                border.color: "#656565"
                border.width: 1
                color: "transparent"
            }
        }

        Rectangle {
            id: barcodeRectangle
            Layout.fillWidth: true
            Layout.fillHeight: true
            border.width: 1
            border.color: "#bdbebf"
            clip: true
            color: "white"

            property int imageWidth: Math.min(height, width) * 0.7;

            Image{
                id:resultImage
                anchors.centerIn: parent
                sourceSize.width: 200
                sourceSize.height: 200

                source: "image://QZXing/encode/" + inputField.text
                cache: false;
            }
        }
    }
}
```

**Comment by ftylitak** [comment]
any updates? if not, it will be closed.
