### ISSUE TITLE
The project lack proper versioning 

### ISSUE THREAD

**Issue by G-S-E** [ftylitak/qzxing#186]
It seems that versions are not going to be assigned any more.

**Comment by ftylitak** [comment]
Hello @G-S-E 

indeed this is a mistake of mine. I wanted to start a proper tracking of the versions and the changes but I blocked myself when trying to write the complete change notes for the past 4 years. I know that it must be done and it is good that you mention it so this issue will remain open till this gets properly handled.

**Comment by ftylitak** [comment]
@G-S-E I just started the tracking of proper versioning which can be checked in [Releases](https://github.com/ftylitak/qzxing/releases). Version [v.3.0.0](https://github.com/ftylitak/qzxing/releases/tag/v3.0.0) has tagged the latest version before Qt 6 support. 

Starting from today, any new feature release will be provided through proper versioning.
