### ISSUE TITLE
Error: 'QtCore/QTextCodec' file not found

### ISSUE THREAD

**Issue by hzxie** [ftylitak/qzxing#187]
https://github.com/ftylitak/qzxing/blob/63850d5f0326aaf7a9bbf6ef276bdc4f4ab583f3/src/QZXing.cpp#L17

qzxing/src/QZXing.cpp:16: did not find header 'QTextCodec' in framework 'QtCore' (loaded from '/Applications/Qt/6.0.0/clang_64/lib')

**Comment by ftylitak** [comment]
I see you are building for Qt 6. 
QTextCodec is in the "Compatibility APIs" so it will be changed at some point in QZXing. Until then you could add the following in your main .pro file.

```pro
QT += core5compat
```

**Comment by hzxie** [comment]
Thanks for your reply.
Actually, I just remind you to port to Qt 6 because `core5compat` will be removed in the future.

**Comment by ftylitak** [comment]
Much appreciated @hzxie! Thanks!
