### ISSUE TITLE
Captured image mirrored on QZXing::decodeImage

### ISSUE THREAD

**Issue by LucaVs** [ftylitak/qzxing#21]
Using  QZXingLive on Android is impossible to decode QR CODE because the QImage passed to QZXing::decodeImage is mirrored.
To check I simply added:
```
    image.save("/storage/emulated/0/bbbb.jpg", "JPG");
```
on the top of decodeImage then opened with a filemanager.
Code 39 is decoded without problem because the image is rotated while decoding but QR CODE has 2 dimensions so rating doesn't solve because of it's mirrored.

**Comment by nickdiego** [comment]
In this case, "tryHarder" must be set to true in QZXingFilter.decoder.

**Comment by LucaVs** [comment]
Thanks,
I confirm it solved.
However, it should be useful to avoid mirrored images to speed up decoding. 
Could it depends on my smartphone (Nexus 5) ?

**Comment by ftylitak** [comment]
Thank you @LucaVs ,

i forgot to close the issue when i committed the change. Thus, i am adding the reference to the commit: 51346e19d620e8033e37451ae01268e8d75fe892
