### ISSUE TITLE
Android 6 Error Permission Camera

### ISSUE THREAD

**Issue by isopen** [ftylitak/qzxing#22]
https://developer.android.com/training/permissions/requesting.html
Build QZXingLive on Android 6.0
Fix. Please :...

**Comment by ftylitak** [comment]
Hello @isopen 

indeed your mark is valid. I have the solution already implemented but it will take a week or so to commit it (may be less i hope). Though, your note can be bypassed for now if you go to the Settings -> Apps -> QZXingLive ->Permissions and you manually allow all the requested permissions. 

As soon as i commit the fix, it will interactively request for permission granting.

Best regards

**Comment by isopen** [comment]
Hello @ftylitak 
QZXing working in a new project on android 6.
The project was created with the help of qt5.6 or qt5.7.
I think you need to create a project on Qt5.7-5.8 and add example.

**Comment by isopen** [comment]
Application qtwidgets.
main.cpp
#include "mainwindow.h"
#include <QApplication>
#include <QZXing.h>
#include <QZXingFilter.h>
int main(int argc, char *argv[])
{
    QZXing::registerQMLTypes();
    QApplication a(argc, argv);
    MainWindow w;
    w.showFullScreen();
    return a.exec();
}
Next
mainwindow.cpp
QQuickWidget *view = new QQuickWidget;
view->setGeometry(0, 0, width, height);
view->setSource(QUrl("qrc:/qml/qrcodereader.qml"));
QLayout->addWidget(view, 0, 0);
Next run
The application is available right at the camera.

**Comment by isopen** [comment]
exemple. run cam on android 6.0
https://github.com/isopen/c/tree/master/qt/qrcode/testqrcode

**Comment by ftylitak** [comment]
@isopen 
QZXingLive project is an example code on how to use QZXing library in QML, not how to use Qt in general. The example that you have added has differences on code parts that do not relate with the library itself.  Thus I do not consider the necessity of any further example project for the time.

Regarding your initial note, I have just made a commit that properly handles the request for application permissions. For me, I consider this issue closed but it will remain open till I get your feedback.

**Comment by isopen** [comment]
@ftylitak
Good job!
https://github.com/ftylitak/qzxing/tree/master/examples/QZXingLive/android/src/org/ftylitak/qzxing

**Comment by ftylitak** [comment]
Closing issue.
