### ISSUE TITLE
Powered by Debian Linux and Windows? (webcam)

### ISSUE THREAD

**Issue by isopen** [ftylitak/qzxing#23]

**Comment by ftylitak** [comment]
Hello @isopen 

can you be more descriptive on what you are trying to say? Always a more detailed description increases the possibility of a good answer.

If you are looking for an example project that you can use in Linux or Windows that will be using the webcam, then again the QZXingLive is the example that you should look for.

**Comment by isopen** [comment]
Linux Debian Log:
GLib-GObject-WARNING **: invalid (NULL) pointer instance
GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
GLib-GObject-WARNING **: invalid (NULL) pointer instance
GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
GLib-GObject-WARNING **: invalid (NULL) pointer instance
GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
GStreamer-CRITICAL **: gst_object_ref_sink: assertion 'GST_IS_OBJECT (object)' failed
GStreamer-CRITICAL **: gst_element_get_bus: assertion 'GST_IS_ELEMENT (element)' failed
GStreamer-CRITICAL **: gst_bus_add_watch_full: assertion 'GST_IS_BUS (bus)' failed
GStreamer-CRITICAL **: gst_bus_set_sync_handler: assertion 'GST_IS_BUS (bus)' failed
GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed
GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed
Focus mode selection is not supported
GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed
GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed
GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

The camera is working in another application.

**Comment by isopen** [comment]
Fix: apt-get install gstreamer0.10-plugins-bad gstreamer0.10-plugins-ugly

Current Log:
Focus mode selection is not supported
Focus points selection is not supported
Focus mode selection is not supported
Focus points mode selection is not supported

**Comment by isopen** [comment]
Fix:
focusMode: CameraFocus.FocusAuto
focusPointMode: CameraFocus.FocusPointAuto
