### ISSUE TITLE
QZXing without QML - Including QML headers

### ISSUE THREAD

**Issue by maurosanjo** [ftylitak/qzxing#26]
When setting the QZXing pri to not add QML:

`CONFIG -= qzxing_qml`

In QZXing.cpp and ImageHandler.cpp there are QML related include files outside #ifdef QZXING_QML scope. This will cause errors if project does not include QML.

**Comment by maurosanjo** [comment]
And if I add them to the inside #ifdef I get several errors since there are a lot of QML related code without a preprocessor directive.

**Comment by ftylitak** [comment]
Hello @maurosanjo 

the project [qzxing/tests/src/QZXingTests/](https://github.com/ftylitak/qzxing/tree/3397ee4a2b60eb60674770f3ca74573759a36c35/tests/src/QZXingTests) already uses this configuration and is working as expected. 

Are you inserting the CONFIG line in the .pro file of your project?
Is it before or after the "include" statement for the QZXing.pri?
Finally, which platform are you targeting and which compiler do you use?

**Comment by maurosanjo** [comment]
Yeap,

I found that putting on my pro file it compiles, but it is still requiring QtQuick and QtQML files, since ImageHandler.cpp still uses it regardless of setting the flag.

**Comment by ftylitak** [comment]
@maurosanjo , 

thank you for point this out. I have just made a change that better isolates the QML dependencies. Could you give it a try and give me your feedback?

**Comment by maurosanjo** [comment]
Works perfectly now! Thanks
