### ISSUE TITLE
about QZXingLive + iOS

### ISSUE THREAD

**Issue by rigoryan** [ftylitak/qzxing#32]
First of all this is great project!
I downloaded example and tried QZXingLive.
I was able to successfully decode bar code with no problem.

I did not modify any source code in example code.
I did add info.plist to enable camera.

I had no success so far on decoding QRCode. 
I am using iphone 7+ as test device.
below is a snippet of qml debug print.

Please advise on what I might be missing.

J

160.37708830548917 419
qml: frame finished: false 120 160.28095238095227 420
qml: frame finished: false 120 160.1852731591448 421
qml: frame finished: false 902 161.9431279620852 422

**Comment by mrAlmond** [comment]
Same problem for me. I'm trying to have an app that reads qrcodes on android and ios.
I've tested QZXingLive on Windows 7 and Android and they both work well (with the only problem that in Android the image processing seems to be slow and the camera view every "certain" seconds freezes for a while).
On iOS (iphone 5c) the app starts correctly and the image processing seems to be smooth, but unfortunately it can only recognize barcodes, qrcodes are not recognized.
Could it be a problem with the camera image resolution (maybe too high)?
Please help, otherwise I will have to choose another library :-(

**Comment by ftylitak** [comment]
Hello @rigoryan @mrAlmond 

indeed i have never tried the library on iOS due to my lack of iOS device. I only had reports of its functionality by people that have already used it. 

I believe that i can acquire an iPhone 7 for the next few days so i will test it and get back to you.

Best regards

**Comment by mrAlmond** [comment]
That would be great. Thank you.

**Comment by rigoryan** [comment]
Thanks too. 
I just ran tests on my galaxy S4, and works smoothly. 

J

**Comment by ftylitak** [comment]
After some tests with the iPhone i saw that the image was flipped and rotated. To commit it properly i need to do some tests and further optimizations. 

Though, if you need  a quick fix for you to continue your development, you can apply the following change: 

```diff
diff --git a/src/QZXingFilter.cpp b/src/QZXingFilter.cpp
index f37100b..3b89613 100644
--- a/src/QZXingFilter.cpp
+++ b/src/QZXingFilter.cpp
@@ -158,7 +159,7 @@ static QImage rgbDataToGrayscale(const uchar* data, const CaptureRect& captureRe
     uchar* pixelInit = image.bits();
     data += (captureRect.startY * captureRect.sourceWidth + captureRect.startX) * stride;
     for (int y = 1; y <= captureRect.targetHeight; ++y) {
-        uchar* pixel = pixelInit + (captureRect.targetHeight - y) * captureRect.targetWidth;
+        uchar* pixel = pixelInit + y * captureRect.targetWidth;
         for (int x = 0; x < captureRect.targetWidth; ++x) {
             uchar r = data[red];
             uchar g = data[green];
```

It would be great if you could give it a try and share your results.

**Comment by rigoryan** [comment]
Again, thanks for quick response and great project.
I confirm the patch works on my iphone 7+ now.

So far, both my galaxy s4 and iphone 7+ work great in daytime when QRCode is shown on my computer screen. I am using a MACBOOK retina screen.

The detection rate dropped when I tried on some product package qrcodes at home in house light condition.

I am wondering whether there are some recommendations on capturing video frames from QML?
E.g. Videofrom/image pre-processing etc.

Just for record,  I am using the following QR test code.
https://www.printbusinesscards.com/marketing/qrcode/QR-Code-Quality-Standards-Test.php

**Comment by mrAlmond** [comment]
Hi thank you for the fast answer. Today I'm going to do some tests with my iphone 5 and I will let you know ASAP.

**Comment by mrAlmond** [comment]
Yes it works! Thank you!
