### ISSUE TITLE
QML: decoder.foundedFormat() is Empty

### ISSUE THREAD

**Issue by anton-dutov** [ftylitak/qzxing#37]
Thanks for awesome project!
 
Trying example on Qt5.9 ARM (Android) on test QrCode

    
    decoder {
        enabledDecoders: QZXing.DecoderFormat_QR_CODE |
                         QZXing.DecoderFormat_PDF_417 |
                         QZXing.DecoderFormat_DATA_MATRIX |
                         QZXing.DecoderFormat_Aztec

        onTagFound: {
            console.log(tag + " | " + decoder.foundedFormat() + " | " + decoder.charSet());
        }

        tryHarder: false
    }

Shows

    (onTagFound): qml: TestTag |  | ISO8859-1

Where foundedFormat is empty, any help?

**Comment by ftylitak** [comment]
Closing this as solved
