### ISSUE TITLE
QtQuick 2 example required

### ISSUE THREAD

**Issue by swex** [ftylitak/qzxing#4]
Hello there.

I think it would be very useful to provide qtquick2 example. Docs are lacking details. What below comment means?
I found Image provider but its not related to Camera Element in any way.

```
   * The decoding function accessible from QML. (Suggested for Qt 5.x)

     * Can be used to decode image from the Camera element preview by providing

     * the following string: image://camera/preview_1

     */

    QString decodeImageQML(const QUrl &imageUrl);
```

**Comment by ftylitak** [comment]
Closing this issue since example project QZXingLive was created.
