### ISSUE TITLE
Extra characters in the decoded text

### ISSUE THREAD

**Issue by NithyeshS** [ftylitak/qzxing#43]
Hi,

I have been playing around with QZXing to create a bar code scanner application. It works perfectly for the most part. But I have noticed an odd behavior with the library. 

Whenever I try to decode a code which has a `(` as the first character, the decoded text has a `]C` in the beginning.
INPUT: (01)95012345678903(3103)000123
OUTPUT ]C01950123456789033103000123

As you can see, there is no issue with a `(` character that occurs in the middle of the code. I have enabled all DecoderFormats in my code. 

Is this a known issue or am I doing something wrong?

**Comment by ftylitak** [comment]
Hello @NithyeshS 

most likely, this behavior relates as a concept to the #36 . 
Could you please attach an example image for me to test it?

**Comment by NithyeshS** [comment]
![barcode 2](https://user-images.githubusercontent.com/11173369/28785657-a5eb56fc-7634-11e7-86b5-b517d14d026e.png)

Thanks for the quick response @ftylitak . I will also try to dig into this.

**Comment by ftylitak** [comment]
Hello @NithyeshS 

sorry for the delay but it just occurred to me. You want to decode the image and get only the numbers without the parenthesis. If this is the case, remove the following decoder format from the activated decoders and you will  be fine: 
```
DecoderFormat_CODE_128_GS1
```

As soon as you try it, please give me  your feedback. 

Best regards.

**Comment by ftylitak** [comment]
Closing this as it has been very long. If it is still an issue, reopen.
