### ISSUE TITLE
MaskUtil 'max' is no element of 'std'

### ISSUE THREAD

**Issue by onek24** [ftylitak/qzxing#53]
When compiling QZXing with Qt 5.9.2 and MSVC2017 64bit(Visual C++ Compiler 15.0) the following error is occuring in MaskUtil.cpp several times:

> C2039: "max" is not an element of "std".

I could fix this by including \<algorithm\> in MaskUtil.cpp

The strange thing is, this error never occured before. This is just occuring after reinstalling by build environment and yet it seems to me like this is a real issue and not a environmental one.

**Comment by ftylitak** [comment]
as confirmed, this is fixed by commit: 5826e86d1b19633c0d3eb873554a18184292ba26
