### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [ftylitak/qzxing#57]

**Comment by ftylitak** [comment]
Hello @ZaMaZaN4iK 

indeed, many of the forks of the project had just been done only to create a CMakeList. 
My free time till the end of the year is close to zero so i will look at it in a couple of months. 

Till then, everyone is welcomed to contribute on this.

**Comment by Simon-Maddison-fd** [comment]
Maybe you can improve on what I have done. I am pretty new to CMake so I am sure there is some improvements that could be made.

**Comment by ftylitak** [comment]
Fixed by #135 .
