### ISSUE TITLE
memory leak in DataMatrixDecodedBitStreamParser.cpp

### ISSUE THREAD

**Issue by GregoryVV** [ftylitak/qzxing#58]
The last line (brackets aside that is) of that file reads

`delete bytes;`

while it should be

`delete [] bytes;`

as the bytes variable was allocated (a few lines higher up) with the new [] operator:

`char* bytes = new char[count];`

**Comment by ftylitak** [comment]
It took me a while, though i have finally made the change. 
Thank you for your comment.
