### ISSUE TITLE
QtCore: No such file or directory

### ISSUE THREAD

**Issue by broadsword007** [ftylitak/qzxing#66]
I get "QtCore: No such file or directory" when I try building my project. If I remove "CONFIG += qzxing_qml" everything works fine but I want to use QML. My Qt version is 5.9 and I tried to build on Ubuntu GCC 64 bit
Here is my .pro file

```qml
    QT += qml quick

    CONFIG += qt c++11

    SOURCES += main.cpp

    RESOURCES += qml.qrc

    QML_IMPORT_PATH =

    QML_DESIGNER_IMPORT_PATH =
    DEFINES += QT_DEPRECATED_WARNINGS

    CONFIG += qzxing_qml
    include(src/QZXing.pri)
    qnx: target.path = /tmp/$${TARGET}/bin
    else: unix:!android: target.path = /opt/$${TARGET}/bin
    !isEmpty(target.path): INSTALLS += target
```

**Comment by ftylitak** [comment]
Helloo @broadsword007 

Could you please pull the latest changes and rerty? 
Does this solves your issue?

**Comment by broadsword007** [comment]
I am still seeing this issue. It might be important that the intellisense does not show the "QtCore: No such file or directory" error in QZXing_global.h, I see the error when I compile.

**Comment by ftylitak** [comment]
@broadsword007 

I believe that it has now been fixed. At least in 2 PCs that I tested, it works. 
Do you confirm?

**Comment by broadsword007** [comment]
Great! it's working now. Thanks a lot.

**Comment by ftylitak** [comment]
Nice to hear. Thank you for reporting the issue.
