### ISSUE TITLE
module "QZXing" is not installed in qml at QT plateform

### ISSUE THREAD

**Issue by mayankdthakor** [ftylitak/qzxing#72]
@ftylitak 
Hi
i succesfully compile the code and i added qzxing folder inside my project but when i run the code QR code is not generated in qml side.

during **runtime** i get this error:  module "QZXing" is not installed

can you please look at my code when i did mistake 

more ever my contain of code is this

in my .pro file i added this 
```pro
CONFIG += qzxing_qml
CONFIG += staticlib

include(QZXing/QZXing.pri)

HEADERS += \
    \home\path\of\my\system\qmlqrcode\qzxing\src \
```

main.cpp file

```cpp
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QZXing.h>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));


    QString data = "text to be encoded";
    QImage barcode = QZXing::encodeData(data);


    return app.exec();
}
```

main.qml file

```qml
import QtQuick 2.7
import QtQuick.Window 2.2
import QZXing 2.3

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Hello World")

    Text {
        text: qsTr("Hello World")
        anchors.centerIn: parent
    }

    Image{
        source: "image://QZXing/encode/" + inputField.text;
        cache: false;
    }
}
```

**Comment by ftylitak** [comment]
Hello @mayankdthakor 

try adding the following two lines in your main.cpp before loading the mail.qml:

``` cpp
QZXing::registerQMLTypes();
QZXing::registerQMLImageProvider(engine);
```

the main would become:
```cpp
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QZXing.h>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    QZXing::registerQMLTypes();
    QZXing::registerQMLImageProvider(engine);

    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    QString data = "text to be encoded";
    QImage barcode = QZXing::encodeData(data);


    return app.exec();
}
```

I consider this as a deficiency of the documentation so I will try to find time to make a more detailed how-to guide.

More over, you do not need to use "CONFIG += staticlib" in the .pro file. This would be used if you had opened QZXing.pro project and built the library as static. In your case it is not needed.

Looking forward to your input.

**Comment by mayankdthakor** [comment]
when i run this i am getting this error in qml file      
**ReferenceError: inputField is not defined**     

this is line number in qml  source: "image://QZXing/encode/" + inputField.text;

i need to add something !!

**Comment by mayankdthakor** [comment]
ok thanks it is working fine for me !!
you are awesome buddy ..!!

**Comment by ftylitak** [comment]
well, this is because there is not **id** in the Text element.

```qml
import QtQuick 2.7
import QtQuick.Window 2.2
import QZXing 2.3

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Hello World")

    Text {
        id: inputField
        text: qsTr("Hello World")
        anchors.centerIn: parent
    }

    Image{
        source: "image://QZXing/encode/" + inputField.text;
        cache: false;
    }
}
```

**Comment by ftylitak** [comment]
Happy to hear :)

I am closing the issue.

**Comment by mayankdthakor** [comment]
Done !!

**Comment by TM9412** [comment]
Hi @ftylitak 

Can you please tell me How this line code is working  ? 
        source: "image://QZXing/encode/" + inputField.text;
