### ISSUE TITLE
encodeData - inverted indexing resulting in mirrored and rotated qr code

### ISSUE THREAD

**Issue by madkrouger** [ftylitak/qzxing#77]
Hi,
ByteMatrix internal representation is height_vector of width_vectors, so to indexing properly it should be bytes[y][x].

I'm referring to  QZXing.cpp:encodeData
```c++
for(int i=0; i<bytesRef->getHeight(); i++)
  for(int j=0; j<bytesRef->getWidth(); j++)
    image.setPixel(j, i, bytes[i][j] ?
```

**Comment by ftylitak** [comment]
Hello @madkrouger 

have you ever run the BarcodeEncoder example? 
With the current implementation, I get the following:

![2018-03-15](https://user-images.githubusercontent.com/550020/37486334-dcb248e8-2896-11e8-8d2b-02a5dd992c89.png)

This image matches with the definition of Qr Code:

![400px-qr_code_structure_example_3 svg](https://user-images.githubusercontent.com/550020/37486660-d344c758-2897-11e8-8118-25f7a7d7bcd6.png)

If you are getting an other result, please provide me examples and I would gladly make changes.

**Comment by madkrouger** [comment]
Hello @ftylitak

Yes, I had had exactly the same result using i.e. BarcodeEncoder, before I changed above code.
Android's NeoReader, for example, cannot decode it, neither QZXingDragNDropTest.

To visualize the issue, this is the same sentence encoded by some web qr generator:

![qr_web](https://user-images.githubusercontent.com/12464843/37491471-41457620-289e-11e8-89e7-22c065e7ecdd.png)
