### ISSUE TITLE
Incorrect encoding of long data

### ISSUE THREAD

**Issue by STLeee** [ftylitak/qzxing#83]
Result of input long data (about 100 chars) with function
`QImage QZXing::encodeData(const QString& data) `
is incorrect QR Code. Even zxing site can't recognize it.

**Comment by ftylitak** [comment]
Hello @STLeee 

could you provide an example character sequence?

Thank you

**Comment by STLeee** [comment]
data = "abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890";
    qDebug() << "data : \n" << data ;
    QImage qrcode = QZXing::encodeData(data );

    QZXing decoder;
    decoder.setDecoder( QZXing::DecoderFormat_QR_CODE );
    QString result = decoder.decodeImage(qrcode);
    qDebug() << "result: \n" << result;

**Comment by STLeee** [comment]
Yes, I tried all I can try

and if I add 
```
EncodeHint hist;
hist.setCharacterSet("UTF-8");
```

and 

```
Ref<qrcode::QRCode> barcode = qrcode::Encoder::encode(
                        data.toStdString(),
                        errorCorrectionLevel == EncodeErrorCorrectionLevel_H ?
                            qrcode::ErrorCorrectionLevel::H :
                        (errorCorrectionLevel == EncodeErrorCorrectionLevel_Q ?
                            qrcode::ErrorCorrectionLevel::Q :
                        (errorCorrectionLevel == EncodeErrorCorrectionLevel_M ?
                             qrcode::ErrorCorrectionLevel::M :
                             qrcode::ErrorCorrectionLevel::L)), &hist);
```
then application will stop like running in infinite loop

**Comment by jimmymorales** [comment]
It is not working for me neither. I tried to encode the _"PM8TJMrnehHcsGDdTh1vawEEyRJrATaJGXQMmy2Jq3ZUmLscKGWZsqxYDwNMi3uftS2T7xrcv5MyvSDWNgwZBjk9JPHQs4uHmrJKJmEHiH9zLyrw1Zmr"_ string, and I already tried three different decoders with no success.

```
Image{
	source: "image://QZXing/encode/"PM8TJMrnehHcsGDdTh1vawEEyRJrATaJGXQMmy2Jq3ZUmLscKGWZsqxYDwNMi3uftS2T7xrcv5MyvSDWNgwZBjk9JPHQs4uHmrJKJmEHiH9zLyrw1Zmr";
	cache: false;
}
```

It works when I encode the _"PM8TJMrnehHcsGDdTh1vawEEyRJrATaJGXQMmy2Jq3ZUmLscKGWZsqxYDwNMi3uftS2T7xrcv5MyvSDWNgwZBjk9JPHQs4uHmrJKJmEHiH"_ string (106 characters long). When I add one more character it doesn't work anymore (107 characters long).

**Comment by ftylitak** [comment]
hello @jimmymorales 

thank you for your report, indeed this is an identified issue though there is no fix yet. 

Regarding your tests with the 106 and 107 characters, did you have consistent failures with the 107 characters with any of the Error Correction Levels? And also consistent successes with the 106 characters?

**Comment by jimmymorales** [comment]
It works with 106 characters long and High ECL, when I add one more character it stops recognizing the QR.
I will test with different correction levels.

**Comment by Kyrw** [comment]
Hi, We're having the same issue. Any ideia when its going to be fixed? Or a hint on how to fix it?

**Comment by fbolduc** [comment]
Hi, Any progress on this? I see the same results as jimmymorales. Works with 106 characters but fails with 107. Thanks.

**Comment by STLeee** [comment]
If you need to use it now, you can use [libqrencode](https://github.com/fukuchi/libqrencode) first.

**Comment by ftylitak** [comment]
Thank you @STLeee  for the suggestion!

@fbolduc indeed the bug is as you mention. For this reason I have created a stress test that encodes and decodes Qr codes (https://github.com/ftylitak/qzxing/blob/master/tests/src/QZXingTests/main.cpp). 
Even though the bug is 100% reproducible, i still have not found its source/solution.

**Comment by data-man** [comment]
Or try [zxing-cpp](https://github.com/nu-book/zxing-cpp).

**Comment by ftylitak** [comment]
Interesting that zxing-cpp has ported the encoding as well. i will take a look at it as soon as i find some time. 

Currently i avoid direct merge with zxing-cpp because it is in C++14 and i would like QZXing to be usable even for platforms that do not yet support new compilers. May be this will change in the future, though for now this is the status.
