### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Bearzeng** [ftylitak/qzxing#88]
Seems there is a memory leak in the code. Just run QZXingLive for ~3 mins, the %MEM increased from 0.6 % to 8.3%, and still increasing !

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                        
 7341 xzeng     20   0 3237452 1.274g  59452 S  57.1  8.3   2:23.62 QZXingLive

**Comment by ftylitak** [comment]
This could be related to the issue #61 .

**Comment by Bearzeng** [comment]
could be, but both release build and debug build have the same issue

**Comment by pasnox** [comment]
@milianw Wanna have a look at it ? you used / improved it a lot in the past ?

**Comment by ftylitak** [comment]
@pasnox  do you also experience this memory increase? throughout my tests I have not seen any memory leak so I am curious, which platform do you target?

**Comment by pasnox** [comment]
@ftylitak I don't, i never used this library yet.

**Comment by milianw** [comment]
@Bearzeng if you can easily reproduce this issue, create a small MWE and then attach it here. Also, please try to run heaptrack on it then (with symbols for QZXing available) and then attach the profile data here too. That way I can easily help out. But I don't have the time currently to invest more on this non-issue for me (I'm not using QZXing actively currently).
