### ISSUE TITLE
How to Change QR Colors?

### ISSUE THREAD

**Issue by Poseyy** [ftylitak/qzxing#89]
Where in the code can someone edit the QR colors from black and white to some other combination? 
Thanks.

**Comment by ftylitak** [comment]
Hello @Poseyy,

for now, this option is not yet available.

Though if you are interested on tweeking the QZXing code you can change the color values at line 521 and 522 in QZXing.cpp https://github.com/ftylitak/qzxing/blob/501e0f87384cf655e38a7a36f99fb510c4a812dc/src/QZXing.cpp#L522

Does this work for you?

**Comment by Poseyy** [comment]
@ftylitak 
Exactly what I was looking for! Thank you.
