### ISSUE TITLE
QZXingLive pixel format

### ISSUE THREAD

**Issue by hungerburg** [ftylitak/qzxing#9]
The camera here natively produces 'GBRG' only, according to `v4l2-ctl --all`
Yet, QZXingLive fails, because it is fed Format_YUV420P.
Can I instruct it to use a working format conversion?

**Comment by ftylitak** [comment]
@hungerburg: could you check that it works as needed?

**Comment by hungerburg** [comment]
Dear Nikolaos, I don't have this camera anymore; I have another one, that produces YUV natively and after having fetched current git origin, I could scan a code successfully!

**Comment by ftylitak** [comment]
I am glad to hear that! 

So, i consider this issue closed :)
